# -*- coding: utf-8 -*-
"""requerimientos3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDkBXO6Sdx-9WyEVr33kjURq3aSP4fIe
"""

streamlit
pandas
numpy
shapely
matplotlib
contextily
imageio
pytz
mplcursors